#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
/*This will move the robot foward 10 rotations at 50% speed. Dunno if thats 5 feet or not,
depends on the size of the wheel, but if it works then hey, 0.2.0 already */
forward(10, rotations, 63);

}
