#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft, reversed)
#pragma config(Motor,  port9,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

  // Sets the leftMotor to MAX power 127
  setMotor(leftMotor, 127);
  // Seets the rightMotor to MAX power 127
  setMotor(rightMotor, 127);
  // Run for 3 seconds
  wait1Msec(3000);

}
